export enum Feature {
  INDIVIDUAL_DASHBOARD = "INDIVIDUAL_DASHBOARD",
  TEAMS = "TEAMS",
  TEAMS_DASHBOARD = "TEAMS_DASHBOARD",
  TEAM_STATISTICS = "TEAM_STATISTICS",
  TEAM_INSIGHTS = "TEAM_INSIGHTS",
  TEAM_CALENDAR = "TEAM_CALENDAR",
  TEAM_PLANNER = "TEAM_PLANNER",
  TEAM_MEMO = "TEAM_MEMO",
}
